# Generated by Django 3.0.2 on 2020-01-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='メイン項目名')),
                ('datetime', models.DateTimeField(verbose_name='日付')),
            ],
            options={
                'db_table': 'mainlist',
            },
        ),
        migrations.CreateModel(
            name='SubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='サブ項目名')),
                ('total_num', models.IntegerField(default=0, verbose_name='総数')),
                ('main_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.MainList')),
            ],
            options={
                'db_table': 'sublist',
            },
        ),
    ]
